import re
seq = "ATGCAATCGACTACGATCAATCGAGGGCCC"
#count the number of fragments that can be generated by EcoRI enzymes
fragment_numbers = re.findall(r"GAATTC",seq)
#one cut generates two fragments
print (int(len(fragments_numbers))+1)
#no "GAATTA" sequence so the DNA sequence is the same